version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - react/install:
        build: npm install && npm start
      - cypress/install:
          build: npm run build
      - cypress/run:
          requires:
            - cypress/install
          command: npm install && npx cypress run --headless --component
