version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: yarn install --frozen-lockfile --ignore-engines
      - cypress/run:
          store_artifacts: true
          yarn: true
          start: yarn install && yarn cypress run --headless --component
          no-workspace: true
          requires:
            - cypress/install
